app/src/main/java/io/statastic/notes/model/Note.java
package io.statastic.notes.model;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Entity
public class Note {
    @Id
    @Column(length = 36, nullable = false)
    private String id;
    @Column(length = 1000, nullable = false)
    private String text;

    @Column()
    private LocalDateTime created;

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
     @JoinTable(
            name = "note_tag",
            joinColumns = @JoinColumn(name = "note_id"),
            inverseJoinColumns = @JoinColumn(name = "tag_id"))
    private Set<Tag> tags = new HashSet<>();

    public Note() {
    }

    public Note(String id, String text) {
        this.id = id;
        this.text = text;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Set<Tag> getTags() {
        return tags;
    }

    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }

    public String getTitle() {
        return text.split("\n")[0];
    }

    public boolean isLink() {
        return text.startsWith("http");
    }

    public String getTextBody() {
        int firstLineBreak = text.indexOf('\n');
        if (firstLineBreak > -1) {
            return text.substring(firstLineBreak+1);
        }
        return "";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Note note = (Note) o;
        return Objects.equals(id, note.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    public LocalDateTime getCreated() {
        return created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }
}

app/src/main/java/io/statastic/notes/model/Tag.java
package io.statastic.notes.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import java.util.Objects;

@Entity
public class Tag {

    @Id
    @Column(length = 36, nullable = false)
    private String id;

    @Column(length = 20, nullable = false, unique = true)
    private String tag;

    public Tag() {
    }

    public Tag(String id, String tag) {
        this.id = id;
        this.tag = tag;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Tag tag = (Tag) o;
        return id.equals(tag.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    public String toString() {
        return tag;
    }
}

app/src/main/java/io/statastic/notes/frontend/LoginServlet.java
package io.statastic.notes.frontend;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet(value = "/login-servlet")
public class LoginServlet extends HttpServlet {
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        resp.sendRedirect(req.getContextPath());
    }
}

app/src/main/java/io/statastic/notes/services/DumpDataServlet.java
package io.statastic.notes.services;

import io.statastic.notes.repository.Repository;
import org.primefaces.shaded.json.JSONArray;

import jakarta.inject.Inject;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Simple Servlet that dumps all Notes to Json.
 *
 * This is a quick and dirty solution for a simple data backup.
 */
@WebServlet(name="dumpData", urlPatterns = "/dumpData")
public class DumpDataServlet extends HttpServlet {

    @Inject
    private Repository repository;

    public void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException {
        JSONArray jsonObject = new JSONArray(repository.getAllNotes());
        jsonObject.write(response.getWriter());
    }
}

app/src/main/webapp/display-note.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:pf="http://primefaces.org/ui">

    <!--@elvariable id="note" type="io.statastic.notes.model.Note"-->
    <div class="notes-card">
        <div class="notes-card-title">
            <c:choose>
                <c:when test="#{note.isLink()}">
                    <h:outputLink value="#{note.title}">
                        <h:outputText value="#{note.title}"/>
                    </h:outputLink>
                </c:when>
                <c:otherwise>
                    <h:outputText value="#{note.title}"/>
                </c:otherwise>
            </c:choose>
        </div>
        <div  style="flex: 10 0 1px;  padding-left: 5px; scroll-padding-right: 5px; white-space: pre-wrap;">
            <h:outputText value="#{note.textBody}"/>
        </div>
        <div class="notes-card-footer">
            <div style="display: flex; flex-direction: row;">
                <c:forEach var="tag" items="#{note.tags}">
                    <pf:chip label="#{tag.tag}" removable="false">
                    </pf:chip>
                </c:forEach>
                <div style="flex: 10 10 100%">
                </div>
                <div>
                    <h:outputText value="#{note.created}">
                    </h:outputText>
                </div>
                <c:if test="${overview.hasWritePermission()}">
                    <pf:commandButton icon="pi pi-pencil" action="#{overview.edit(note.id)}" class="flex ui-priority-primary"/>
                    <pf:commandButton icon="pi pi-times" action="#{overview.delete(note.id)}">
                        <pf:confirm header="Confirmation" message="Are you sure?" icon="pi pi-exclamation-triangle" />
                    </pf:commandButton>
                </c:if>
            </div>
        </div>
    </div>

</html>

app/src/main/webapp/edit-note.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:pf="http://primefaces.org/ui">
<h:form>
    <div class="notes-card">
        <!--@elvariable id="editedNote" type="io.statastic.notes.frontend.EditedNote"-->
        <pf:inputTextarea value="#{editedNote.text}" style="flex: 10 10 100px;"/>
        <div class="notes-card-footer" style="display: flex; flex-direction: row">
            <pf:chips value="#{editedNote.tags}" style="flex: 10 10 100px;">
            </pf:chips>
            <pf:commandButton icon="pi pi-check" action="#{overview.save}" style="flex: 0 0 30px;"/>
        </div>
    </div>
</h:form>
</html>

app/src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:pf="http://primefaces.org/ui">
<h:head>
    <title>Notes taken, Traces left</title>
    <style>
        .notes-card {
            display: flex;
            flex-direction: column;
            margin: 5px; border-style: solid;
            border-width: 2px;
            border-radius: 10px;
        }
        .notes-card-title {
            flex: 0 0 1px;
            font-weight: bold;
            padding-left: 5px;
            padding-right: 5px;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
        }
        .notes-card-footer {
            flex: 0 0 1px;
            padding-left: 5px;
            scroll-padding-right: 5px;
            padding-bottom: 5px;
            border-bottom-left-radius: 8px;
            border-bottom-right-radius: 8px;
        }
        .ui-chips input {
            padding: 5px;
            width: 100px;
        }
        .ui-card {
            border-style: solid;
            border-width: 3px;
            border-radius: 5px;
            border-color: blue;
            background-color: lightblue;
            padding: 5px;
            width: 300px;
            height: 200px;
        }
        .ui-chip-text {
            padding-right: 5px;
        }
        .ui-chip {
            border-radius: 10px;
            background-color: blue;
            color: white;
            margin-left: 5px;
            margin-right: 5px;
            padding-right: 5px;
            padding-left: 5px;
        }
        textarea {
            resize: none;
        }
    </style>
</h:head>
<h:body style="max-width: 1200px; margin: auto;">
    <div style="display: flex; justify-content:center">
        <div>
        <span style="font-size: xx-large">Notes taken, Traces left</span>
        (<c:choose>
            <c:when test="${overview.hasWritePermission()}"><h:outputText value="#{overview.user}"/></c:when>
            <c:otherwise><a href="login-servlet">login</a></c:otherwise>
        </c:choose>)
        </div>
    </div>
    <div style="display: flex; flex-direction: column;">
        <c:forEach var="note" items="#{overview.notes}">
            <c:choose>
            <c:when test="${overview.isEditing(note.id)}">
                <ui:include src="edit-note.xhtml">
                    <ui:param name="editedNote" value="#{overview.editedNote}" />
                </ui:include>
            </c:when>
            <c:otherwise>
                <ui:include src="display-note.xhtml">
                    <ui:param name="note" value="#{note}" />
                </ui:include>
            </c:otherwise>
        </c:choose>
        </c:forEach>
        <c:if test="${overview.getShowNewNote()}">
            <ui:include src="edit-note.xhtml">
                <ui:param name="editedNote" value="#{overview.editedNote}" />
            </ui:include>
        </c:if>
    </div>
    <pf:confirmDialog global="true" showEffect="fade" hideEffect="fade">
        <pf:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
        <pf:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-times" />
    </pf:confirmDialog>
</h:body>
</html>